{
 "title": "Elrond - All Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Current Epoch Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shard 0 - Validator Nonce",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_nonce{shardID=\"0\"}",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Shard 1 - Validator Nonce",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_nonce{shardID=\"1\"}",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Shard 2 - Validator Nonce",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_nonce{shardID=\"2\"}",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  { "title": "Total Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Leader Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_failure / elrond_node_r_total_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Leader Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Leader Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_failure / elrond_node_r_total_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Validator Total Rating",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_rating",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Validator Ignored Signatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_validator_ignored_signatures",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_ignored_signatures",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  }
 ]
}