{
 "title": "Elrond Remote",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rating Modifier",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,elrond_node_r_rating_modifier)",
     "legendFormat": "{{ displayName }}"
    }
   ]
  },
  {
   "title": "Current Epoch Rating",
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "targets": [
    { "expr": "elrond_node_r_epoch_rating", "legendFormat": "{{ displayName }}" }
   ]
  },
  {
   "title": "Total Rating",
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 3 },
   "targets": [
    { "expr": "elrond_node_r_total_rating", "legendFormat": "{{ displayName }}" }
   ]
  },
  {
   "title": "Validator Shard ID",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "elrond_node_r_shard_id", "legendFormat": "{{ displayName }}" }
   ]
  },
  { "title": "Current Epoch Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Epoch Leader Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_leader_failure / elrond_node_r_epoch_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Leader Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Leader Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_leader_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Validator Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_validator_failure / elrond_node_r_epoch_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Validator Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Validator Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_validator_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  { "title": "Total Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Leader Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_failure / elrond_node_r_total_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Leader Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Leader Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_leader_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Failure/Success Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_failure / elrond_node_r_total_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_success",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_failure",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Validator Total Rating",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_rating",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Current Epoch Validator Ignored Signatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_epoch_validator_ignored_signatures",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elrond_node_r_total_validator_ignored_signatures",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  }
 ]
}