{
 "title": "Elrond - Nodes Table",
 "tags": [ "elrondpublic" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "displayName",
    "label": "Display Name",
    "query": "label_values(elrond_node_r_nonce,displayName)"
   },
   {
    "name": "identity",
    "label": "Identity",
    "query": "label_values(elrond_node_r_nonce,identity)"
   },
   {
    "name": "shardID",
    "label": "Shard ID",
    "query": "label_values(elrond_node_r_nonce,shardID)"
   },
   {
    "name": "nodeType",
    "label": "Node Type",
    "query": "label_values(elrond_node_r_nonce,nodeType)"
   },
   {
    "name": "isActive",
    "label": "Active",
    "query": "label_values(elrond_node_r_nonce,isActive)"
   },
   {
    "name": "network",
    "label": "Network",
    "query": "label_values(elrond_node_r_nonce,network)"
   }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elrond_obs_epochNumber{network=\"$network\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Active Nodes (by Type)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{isActive=\"true\", nodeType=~\"$nodeType\", network=\"$network\"})"
    }
   ]
  },
  {
   "title": "Inactive Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{isActive=\"false\", network=\"$network\"})"
    }
   ]
  },
  {
   "title": "Nodes# - Meta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"meta\", isActive=\"true\", network=\"$network\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"meta\", isActive=\"false\", network=\"$network\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard0",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"0\", isActive=\"true\", network=\"$network\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"0\", isActive=\"false\", network=\"$network\"})",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"1\", isActive=\"true\", network=\"$network\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"1\", isActive=\"false\", network=\"$network\"})",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"2\", isActive=\"true\", network=\"$network\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"2\", isActive=\"false\", network=\"$network\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Elrond Nodes",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "elrond_node_r_nonce{identity=~\"$identity\", shardID=~\"$shardID\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\", network=\"$network\"}"
    }
   ]
  }
 ]
}