{
 "title": "Elrond Testnet - Validator Stats",
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "displayName",
    "label": "Display Name",
    "query": "label_values(elrond_node_r_nonce,displayName)"
   },
   {
    "name": "identity",
    "label": "Identity",
    "query": "label_values(elrond_node_r_nonce,identity)"
   },
   {
    "name": "shardID",
    "label": "Shard ID",
    "query": "label_values(elrond_node_r_nonce,shardID)"
   },
   {
    "name": "nodeType",
    "label": "Node Type",
    "query": "label_values(elrond_node_r_nonce,nodeType)"
   },
   {
    "name": "isActive",
    "label": "Active",
    "query": "label_values(elrond_node_r_nonce,isActive)"
   }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "elrond_obs_epochNumber", "legendFormat": "Epoch" }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{isActive=\"true\"})"
    }
   ]
  },
  {
   "title": "Inactive Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{isActive=\"false\"})"
    }
   ]
  },
  {
   "title": "Nodes# - Meta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"meta\", isActive=\"true\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"meta\", isActive=\"false\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"1\", isActive=\"true\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"1\", isActive=\"false\"})",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard0",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"0\", isActive=\"true\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"0\", isActive=\"false\"})",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Nodes# - Shard2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"2\", isActive=\"true\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "count(elrond_node_r_nonce{shardID=\"2\", isActive=\"false\"})",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "TOP 15 Downtime",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15,elrond_node_r_total_downtime_sec{identity=~\"$identity\", shardID=~\"$shardID\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "TOP 15 Uptime",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(15,elrond_node_r_total_uptime_sec{identity=~\"$identity\", shardID=~\"$shardID\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "TOP 15 Behind",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bottomk(15,elrond_node_r_nonce{identity=~\"$identity\", shardID=~\"$shardID\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  { "title": "Current Epoch Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Shard META  - Validator Nonce (Last 30 Validators by filters)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bottomk(30,elrond_node_r_nonce{shardID=\"meta\", identity=~\"$identity\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Shard 0 - Validator Nonce (Last 30 Validators by filters)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bottomk(30,elrond_node_r_nonce{shardID=\"0\", identity=~\"$identity\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Shard 1 - Validator Nonce (Last 30 Validators by filters)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bottomk(30,elrond_node_r_nonce{shardID=\"1\", identity=~\"$identity\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  },
  {
   "title": "Shard 2 - Validator Nonce (Last 30 Validators by filters)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bottomk(30,elrond_node_r_nonce{shardID=\"2\", identity=~\"$identity\", nodeType=~\"$nodeType\", displayName=~\"$displayName\", isActive=~\"$isActive\"})",
     "legendFormat": "{{ displayName }}, {{nodeType}}, Shard: {{shardID}}"
    }
   ]
  }
 ]
}