{
 "title": "Elrond-Local",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "observer", "query": "Easy2Stake-obs" }
  ]
 },
 "panels": [
  {
   "title": "Epoch Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_epoch_number{displayName=\"$observer\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_nonce{displayName=\"$observer\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_chain_id{displayName=\"$observer\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Connected nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_nodes{displayName=\"$observer\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Validators Live",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_live_validators{displayName=\"$observer\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "#Shards + Meta",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elrond_node_num_shards_wo_meta{displayName=\"$observer\"} + 1",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Shard ID",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "elrond_node_shard_id", "legendFormat": "{{displayName}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "elrond_node_peers", "legendFormat": "{{displayName}}" }
   ]
  },
  {
   "title": "Nonce Shard 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_nonce{shardID=\"0\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Shard 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_nonce{shardID=\"1\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Shard 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_nonce{shardID=\"2\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Meta Shard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_nonce{shardID=\"meta\"}"
    }
   ]
  },
  {
   "title": "Nonce Shard 0 (Nonce/6s - Rate  over 10m Window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elrond_node_nonce{shardID=\"0\"}[10m]) * 6",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Shard 1 (Nonce/6s - Rate  over 10m Window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elrond_node_nonce{shardID=\"1\"}[10m]) * 6",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Shard 2 (Nonce/6s - Rate  over 10m Window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elrond_node_nonce{shardID=\"2\"}[10m]) * 6",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce Meta Shard (Nonce/6s - Rate  over 10m Window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elrond_node_nonce{shardID=\"meta\"}[10m]) * 6",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "elrond_node_peers", "legendFormat": "{{displayName}}" }
   ]
  },
  {
   "title": "Data Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "elrond_node_net_rx_bps", "legendFormat": "RX Traffic {{displayName}}" },
    { "expr": "elrond_node_net_tx_bps * -1", "legendFormat": "TX Traffic {{displayName}}" }
   ]
  },
  {
   "title": "Shard Headers In Pool",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_shard_headers_in_pool",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce/6s - Rate  over 10m Window - ALL Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(elrond_node_nonce[10m]) * 6",
     "legendFormat": "{{displayName}}, ShardID: {{shardID}}"
    }
   ]
  },
  {
   "title": "Syncing Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "elrond_node_sync_status", "legendFormat": "{{source}}: {{displayName}}" }
   ]
  },
  {
   "title": "Validator Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_type{nodeType=\"validator\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Nonce - ALL Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "elrond_node_nonce",
     "legendFormat": "{{displayName}}, ShardID: {{shardID}}"
    }
   ]
  },
  {
   "title": "Systemd Service Status - Active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"elrond-node-[0-9].service\", state=\"active\"}",
     "legendFormat": "{{source}}: {{name}}"
    },
    {
     "expr": "node_systemd_unit_state{name=~\"elrond-node-[0-9].service\", state=\"active\"}",
     "legendFormat": "{{source}}: {{name}}"
    }
   ]
  },
  {
   "title": "Systemd Service Status - Other than Active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"elrond-node-[0-9].service\", state!=\"active\"}",
     "legendFormat": "{{source}}: {{name}}, {{state}}"
    },
    {
     "expr": "node_systemd_unit_state{name=~\"elrond-node-[0-9].service\", state!=\"active\"}",
     "legendFormat": "{{source}}: {{name}}, {{state}}"
    }
   ]
  }
 ]
}